name: Docker Build

on:
  push:
    branches: ['**']  # ALL branches
    tags:
      - 'v*'
      - '*.*.*'
  workflow_dispatch:

env:
  PROJECTNAME: search

jobs:
  build-standard:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Set up Docker Buildx
        run: docker buildx create --use --name builder --driver docker-container

      - name: Set build info
        run: |
          echo "COMMIT_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "YYMM=$(date +"%y%m")" >> $GITHUB_ENV
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
            echo "VERSION=${VERSION#v}" >> $GITHUB_ENV
            echo "IS_TAG=true" >> $GITHUB_ENV
          else
            echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
            echo "IS_TAG=false" >> $GITHUB_ENV
          fi
          echo "BUILD_DATE=$(date +"%a %b %d, %Y at %H:%M:%S %Z")" >> $GITHUB_ENV
          # OFFICIALSITE (optional): Set in repository secrets, or site.txt file, or leave empty
          # Never guess or assume - must be explicitly defined by user
          if [ -f site.txt ]; then
            echo "OFFICIALSITE=$(cat site.txt)" >> $GITHUB_ENV
          else
            echo "OFFICIALSITE=${{ secrets.OFFICIALSITE }}" >> $GITHUB_ENV
          fi

      - name: Determine registry and tags (standard)
        id: tags
        run: |
          # Use Gitea container registry
          REGISTRY="${GITHUB_SERVER_URL#https://}"
          REGISTRY="${REGISTRY#http://}"
          IMAGE="${REGISTRY}/${GITHUB_REPOSITORY}"
          TAGS="${IMAGE}:${{ env.COMMIT_ID }}"

          if [[ "${{ env.IS_TAG }}" == "true" ]]; then
            TAGS="$TAGS,${IMAGE}:${{ env.VERSION }}"
            TAGS="$TAGS,${IMAGE}:latest"
            TAGS="$TAGS,${IMAGE}:${{ env.YYMM }}"
          else
            TAGS="$TAGS,${IMAGE}:devel"
            if [[ "${{ github.ref }}" == refs/heads/beta ]]; then
              TAGS="$TAGS,${IMAGE}:beta"
            fi
          fi

          echo "tags=$TAGS" >> $GITHUB_OUTPUT
          echo "registry=$REGISTRY" >> $GITHUB_OUTPUT

      - name: Log in to Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login "${{ steps.tags.outputs.registry }}" \
            -u "${{ github.actor }}" --password-stdin

      - name: Build and push (standard)
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --file docker/Dockerfile \
            --build-arg VERSION=${{ env.VERSION }} \
            --build-arg BUILD_DATE="${{ env.BUILD_DATE }}" \
            --build-arg COMMIT_ID=${{ env.COMMIT_ID }} \
            --build-arg OFFICIALSITE="${{ env.OFFICIALSITE }}" \
            --label "org.opencontainers.image.vendor=apimgr" \
            --label "org.opencontainers.image.authors=apimgr" \
            --label "org.opencontainers.image.title=${{ env.PROJECTNAME }}" \
            --label "org.opencontainers.image.base.name=${{ env.PROJECTNAME }}" \
            --label "org.opencontainers.image.description=${{ env.PROJECTNAME }} - standard image (alpine)" \
            --label "org.opencontainers.image.version=${{ env.VERSION }}" \
            --label "org.opencontainers.image.created=${{ env.BUILD_DATE }}" \
            --label "org.opencontainers.image.revision=${{ env.COMMIT_ID }}" \
            --label "org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }}" \
            --label "org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}" \
            --label "org.opencontainers.image.documentation=${{ github.server_url }}/${{ github.repository }}" \
            --label "org.opencontainers.image.licenses=MIT" \
            --tag $(echo "${{ steps.tags.outputs.tags }}" | sed 's/,/ --tag /g') \
            --push \
            .

  build-aio:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Set up Docker Buildx
        run: docker buildx create --use --name builder-aio --driver docker-container

      - name: Set build info
        run: |
          echo "COMMIT_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "YYMM=$(date +"%y%m")" >> $GITHUB_ENV
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
            echo "VERSION=${VERSION#v}" >> $GITHUB_ENV
            echo "IS_TAG=true" >> $GITHUB_ENV
          else
            echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
            echo "IS_TAG=false" >> $GITHUB_ENV
          fi
          echo "BUILD_DATE=$(date +"%a %b %d, %Y at %H:%M:%S %Z")" >> $GITHUB_ENV
          # OFFICIALSITE (optional): Set in repository secrets, or site.txt file, or leave empty
          # Never guess or assume - must be explicitly defined by user
          if [ -f site.txt ]; then
            echo "OFFICIALSITE=$(cat site.txt)" >> $GITHUB_ENV
          else
            echo "OFFICIALSITE=${{ secrets.OFFICIALSITE }}" >> $GITHUB_ENV
          fi

      - name: Determine registry and tags (all-in-one)
        id: tags
        run: |
          # Use Gitea container registry
          REGISTRY="${GITHUB_SERVER_URL#https://}"
          REGISTRY="${REGISTRY#http://}"
          AIO_IMAGE="${REGISTRY}/${GITHUB_REPOSITORY}-aio"
          TAGS="${AIO_IMAGE}:${{ env.COMMIT_ID }}"

          if [[ "${{ env.IS_TAG }}" == "true" ]]; then
            TAGS="$TAGS,${AIO_IMAGE}:${{ env.VERSION }}"
            TAGS="$TAGS,${AIO_IMAGE}:latest"
            TAGS="$TAGS,${AIO_IMAGE}:${{ env.YYMM }}"
          else
            TAGS="$TAGS,${AIO_IMAGE}:devel"
            if [[ "${{ github.ref }}" == refs/heads/beta ]]; then
              TAGS="$TAGS,${AIO_IMAGE}:beta"
            fi
          fi

          echo "tags=$TAGS" >> $GITHUB_OUTPUT
          echo "registry=$REGISTRY" >> $GITHUB_OUTPUT

      - name: Log in to Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login "${{ steps.tags.outputs.registry }}" \
            -u "${{ github.actor }}" --password-stdin

      - name: Build and push (all-in-one)
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --file docker/Dockerfile.aio \
            --build-arg VERSION=${{ env.VERSION }} \
            --build-arg BUILD_DATE="${{ env.BUILD_DATE }}" \
            --build-arg COMMIT_ID=${{ env.COMMIT_ID }} \
            --build-arg OFFICIALSITE="${{ env.OFFICIALSITE }}" \
            --label "org.opencontainers.image.vendor=apimgr" \
            --label "org.opencontainers.image.authors=apimgr" \
            --label "org.opencontainers.image.title=${{ env.PROJECTNAME }}-aio" \
            --label "org.opencontainers.image.description=${{ env.PROJECTNAME }} - all-in-one (debian + postgresql + valkey + tor)" \
            --label "org.opencontainers.image.version=${{ env.VERSION }}" \
            --label "org.opencontainers.image.created=${{ env.BUILD_DATE }}" \
            --label "org.opencontainers.image.revision=${{ env.COMMIT_ID }}" \
            --label "org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }}" \
            --label "org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}" \
            --label "org.opencontainers.image.documentation=${{ github.server_url }}/${{ github.repository }}" \
            --label "org.opencontainers.image.licenses=MIT" \
            --tag $(echo "${{ steps.tags.outputs.tags }}" | sed 's/,/ --tag /g') \
            --push \
            .
