package bangs

// defaultBangs contains the built-in bang definitions
var defaultBangs = []*Bang{
	// ============================================================================
	// GENERAL SEARCH ENGINES
	// ============================================================================
	{Shortcut: "g", Name: "Google", URL: "https://www.google.com/search?q={query}", Category: "general", Aliases: []string{"google"}},
	{Shortcut: "ddg", Name: "DuckDuckGo", URL: "https://duckduckgo.com/?q={query}", Category: "general", Aliases: []string{"duckduckgo", "duck"}},
	{Shortcut: "b", Name: "Bing", URL: "https://www.bing.com/search?q={query}", Category: "general", Aliases: []string{"bing"}},
	{Shortcut: "sp", Name: "Startpage", URL: "https://www.startpage.com/do/search?q={query}", Category: "general", Aliases: []string{"startpage"}},
	{Shortcut: "q", Name: "Qwant", URL: "https://www.qwant.com/?q={query}", Category: "general", Aliases: []string{"qwant"}},
	{Shortcut: "ec", Name: "Ecosia", URL: "https://www.ecosia.org/search?q={query}", Category: "general", Aliases: []string{"ecosia"}},
	{Shortcut: "br", Name: "Brave Search", URL: "https://search.brave.com/search?q={query}", Category: "general", Aliases: []string{"brave"}},
	{Shortcut: "ya", Name: "Yandex", URL: "https://yandex.com/search/?text={query}", Category: "general", Aliases: []string{"yandex"}},
	{Shortcut: "bd", Name: "Baidu", URL: "https://www.baidu.com/s?wd={query}", Category: "general", Aliases: []string{"baidu"}},
	{Shortcut: "swisscows", Name: "Swisscows", URL: "https://swisscows.com/web?query={query}", Category: "general"},
	{Shortcut: "mojeek", Name: "Mojeek", URL: "https://www.mojeek.com/search?q={query}", Category: "general"},
	{Shortcut: "metager", Name: "MetaGer", URL: "https://metager.org/meta/meta.ger3?eingabe={query}", Category: "general"},
	{Shortcut: "gibiru", Name: "Gibiru", URL: "https://gibiru.com/results.html?q={query}", Category: "general"},
	{Shortcut: "yep", Name: "Yep", URL: "https://yep.com/web?q={query}", Category: "general"},
	{Shortcut: "kagi", Name: "Kagi", URL: "https://kagi.com/search?q={query}", Category: "general"},
	{Shortcut: "you", Name: "You.com", URL: "https://you.com/search?q={query}", Category: "general"},
	{Shortcut: "perplexity", Name: "Perplexity", URL: "https://www.perplexity.ai/search?q={query}", Category: "general", Aliases: []string{"pplx"}},
	{Shortcut: "presearch", Name: "Presearch", URL: "https://presearch.com/search?q={query}", Category: "general"},
	{Shortcut: "naver", Name: "Naver", URL: "https://search.naver.com/search.naver?query={query}", Category: "general"},
	{Shortcut: "sogou", Name: "Sogou", URL: "https://www.sogou.com/web?query={query}", Category: "general"},
	{Shortcut: "ask", Name: "Ask.com", URL: "https://www.ask.com/web?q={query}", Category: "general"},
	{Shortcut: "aol", Name: "AOL Search", URL: "https://search.aol.com/aol/search?q={query}", Category: "general"},
	{Shortcut: "yahoo", Name: "Yahoo", URL: "https://search.yahoo.com/search?p={query}", Category: "general", Aliases: []string{"y"}},
	{Shortcut: "lycos", Name: "Lycos", URL: "https://search.lycos.com/web/?q={query}", Category: "general"},

	// ============================================================================
	// IMAGE SEARCH
	// ============================================================================
	{Shortcut: "gi", Name: "Google Images", URL: "https://www.google.com/search?tbm=isch&q={query}", Category: "images", Aliases: []string{"gimg", "googleimages"}},
	{Shortcut: "bi", Name: "Bing Images", URL: "https://www.bing.com/images/search?q={query}", Category: "images", Aliases: []string{"bingimages"}},
	{Shortcut: "yi", Name: "Yandex Images", URL: "https://yandex.com/images/search?text={query}", Category: "images", Aliases: []string{"yandeximages"}},
	{Shortcut: "fl", Name: "Flickr", URL: "https://www.flickr.com/search/?text={query}", Category: "images", Aliases: []string{"flickr"}},
	{Shortcut: "us", Name: "Unsplash", URL: "https://unsplash.com/s/photos/{query}", Category: "images", Aliases: []string{"unsplash"}},
	{Shortcut: "pexels", Name: "Pexels", URL: "https://www.pexels.com/search/{query}/", Category: "images"},
	{Shortcut: "pixabay", Name: "Pixabay", URL: "https://pixabay.com/images/search/{query}/", Category: "images"},
	{Shortcut: "500px", Name: "500px", URL: "https://500px.com/search?q={query}&type=photos", Category: "images"},
	{Shortcut: "pinterest", Name: "Pinterest", URL: "https://www.pinterest.com/search/pins/?q={query}", Category: "images", Aliases: []string{"pin"}},
	{Shortcut: "imgur", Name: "Imgur", URL: "https://imgur.com/search?q={query}", Category: "images"},
	{Shortcut: "deviantart", Name: "DeviantArt", URL: "https://www.deviantart.com/search?q={query}", Category: "images", Aliases: []string{"da"}},
	{Shortcut: "artstation", Name: "ArtStation", URL: "https://www.artstation.com/search?query={query}", Category: "images"},
	{Shortcut: "behance", Name: "Behance", URL: "https://www.behance.net/search/projects?search={query}", Category: "images"},
	{Shortcut: "dribbble", Name: "Dribbble", URL: "https://dribbble.com/search/{query}", Category: "images"},
	{Shortcut: "giphy", Name: "Giphy", URL: "https://giphy.com/search/{query}", Category: "images", Aliases: []string{"gif"}},
	{Shortcut: "tenor", Name: "Tenor GIFs", URL: "https://tenor.com/search/{query}", Category: "images"},
	{Shortcut: "tineye", Name: "TinEye", URL: "https://tineye.com/search/?url={query}", Category: "images"},
	{Shortcut: "icons8", Name: "Icons8", URL: "https://icons8.com/icons/set/{query}", Category: "images"},
	{Shortcut: "flaticon", Name: "Flaticon", URL: "https://www.flaticon.com/search?word={query}", Category: "images"},
	{Shortcut: "iconfinder", Name: "Iconfinder", URL: "https://www.iconfinder.com/search?q={query}", Category: "images"},
	{Shortcut: "freepik", Name: "Freepik", URL: "https://www.freepik.com/search?query={query}", Category: "images"},
	{Shortcut: "stocksnap", Name: "StockSnap", URL: "https://stocksnap.io/search/{query}", Category: "images"},
	{Shortcut: "openclipart", Name: "OpenClipart", URL: "https://openclipart.org/search/?query={query}", Category: "images"},
	{Shortcut: "wikimediacommons", Name: "Wikimedia Commons", URL: "https://commons.wikimedia.org/w/index.php?search={query}", Category: "images", Aliases: []string{"wmc"}},

	// ============================================================================
	// VIDEO SEARCH
	// ============================================================================
	{Shortcut: "yt", Name: "YouTube", URL: "https://www.youtube.com/results?search_query={query}", Category: "video", Aliases: []string{"youtube"}},
	{Shortcut: "v", Name: "Vimeo", URL: "https://vimeo.com/search?q={query}", Category: "video", Aliases: []string{"vimeo"}},
	{Shortcut: "dtube", Name: "Dailymotion", URL: "https://www.dailymotion.com/search/{query}", Category: "video", Aliases: []string{"dailymotion", "dm"}},
	{Shortcut: "pt", Name: "PeerTube", URL: "https://sepiasearch.org/search?search={query}", Category: "video", Aliases: []string{"peertube"}},
	{Shortcut: "od", Name: "Odysee", URL: "https://odysee.com/$/search?q={query}", Category: "video", Aliases: []string{"odysee", "lbry"}},
	{Shortcut: "rumble", Name: "Rumble", URL: "https://rumble.com/search/video?q={query}", Category: "video"},
	{Shortcut: "bitchute", Name: "BitChute", URL: "https://www.bitchute.com/search/?query={query}", Category: "video"},
	{Shortcut: "twitch", Name: "Twitch", URL: "https://www.twitch.tv/search?term={query}", Category: "video"},
	{Shortcut: "tiktok", Name: "TikTok", URL: "https://www.tiktok.com/search?q={query}", Category: "video", Aliases: []string{"tt"}},
	{Shortcut: "gv", Name: "Google Video", URL: "https://www.google.com/search?tbm=vid&q={query}", Category: "video", Aliases: []string{"googlevideo"}},
	{Shortcut: "bv", Name: "Bing Video", URL: "https://www.bing.com/videos/search?q={query}", Category: "video", Aliases: []string{"bingvideo"}},
	{Shortcut: "veoh", Name: "Veoh", URL: "https://www.veoh.com/find/{query}", Category: "video"},
	{Shortcut: "metacafe", Name: "Metacafe", URL: "https://www.metacafe.com/videos_about/{query}", Category: "video"},
	{Shortcut: "nebula", Name: "Nebula", URL: "https://nebula.tv/search?q={query}", Category: "video"},
	{Shortcut: "floatplane", Name: "Floatplane", URL: "https://www.floatplane.com/search?query={query}", Category: "video"},

	// ============================================================================
	// MAPS & LOCATION
	// ============================================================================
	{Shortcut: "gm", Name: "Google Maps", URL: "https://www.google.com/maps/search/{query}", Category: "maps", Aliases: []string{"gmaps", "googlemaps"}},
	{Shortcut: "osm", Name: "OpenStreetMap", URL: "https://www.openstreetmap.org/search?query={query}", Category: "maps", Aliases: []string{"openstreetmap"}},
	{Shortcut: "bm", Name: "Bing Maps", URL: "https://www.bing.com/maps?q={query}", Category: "maps", Aliases: []string{"bingmaps"}},
	{Shortcut: "apple", Name: "Apple Maps", URL: "https://maps.apple.com/?q={query}", Category: "maps", Aliases: []string{"applemaps"}},
	{Shortcut: "here", Name: "HERE WeGo", URL: "https://wego.here.com/search/{query}", Category: "maps", Aliases: []string{"herewego"}},
	{Shortcut: "waze", Name: "Waze", URL: "https://www.waze.com/live-map/directions?q={query}", Category: "maps"},
	{Shortcut: "mapquest", Name: "MapQuest", URL: "https://www.mapquest.com/search/{query}", Category: "maps"},
	{Shortcut: "yelp", Name: "Yelp", URL: "https://www.yelp.com/search?find_desc={query}", Category: "maps"},
	{Shortcut: "tripadvisor", Name: "TripAdvisor", URL: "https://www.tripadvisor.com/Search?q={query}", Category: "maps", Aliases: []string{"ta"}},
	{Shortcut: "foursquare", Name: "Foursquare", URL: "https://foursquare.com/explore?q={query}", Category: "maps", Aliases: []string{"4sq"}},
	{Shortcut: "gmapsat", Name: "Google Maps Satellite", URL: "https://www.google.com/maps/search/{query}?hl=en&layer=s", Category: "maps"},
	{Shortcut: "gearth", Name: "Google Earth", URL: "https://earth.google.com/web/search/{query}", Category: "maps"},

	// ============================================================================
	// NEWS
	// ============================================================================
	{Shortcut: "gn", Name: "Google News", URL: "https://news.google.com/search?q={query}", Category: "news", Aliases: []string{"gnews", "googlenews"}},
	{Shortcut: "bn", Name: "Bing News", URL: "https://www.bing.com/news/search?q={query}", Category: "news", Aliases: []string{"bingnews"}},
	{Shortcut: "yn", Name: "Yahoo News", URL: "https://news.search.yahoo.com/search?p={query}", Category: "news", Aliases: []string{"yahoonews"}},
	{Shortcut: "reuters", Name: "Reuters", URL: "https://www.reuters.com/search/news?blob={query}", Category: "news"},
	{Shortcut: "ap", Name: "AP News", URL: "https://apnews.com/search?q={query}", Category: "news", Aliases: []string{"apnews"}},
	{Shortcut: "bbc", Name: "BBC", URL: "https://www.bbc.co.uk/search?q={query}", Category: "news"},
	{Shortcut: "cnn", Name: "CNN", URL: "https://www.cnn.com/search?q={query}", Category: "news"},
	{Shortcut: "nyt", Name: "New York Times", URL: "https://www.nytimes.com/search?query={query}", Category: "news", Aliases: []string{"newyorktimes"}},
	{Shortcut: "wapo", Name: "Washington Post", URL: "https://www.washingtonpost.com/search/?query={query}", Category: "news"},
	{Shortcut: "guardian", Name: "The Guardian", URL: "https://www.theguardian.com/search?q={query}", Category: "news"},
	{Shortcut: "aljazeera", Name: "Al Jazeera", URL: "https://www.aljazeera.com/search/{query}", Category: "news", Aliases: []string{"aj"}},
	{Shortcut: "npr", Name: "NPR", URL: "https://www.npr.org/search?query={query}", Category: "news"},
	{Shortcut: "techcrunch", Name: "TechCrunch", URL: "https://techcrunch.com/search/{query}", Category: "news", Aliases: []string{"tc"}},
	{Shortcut: "verge", Name: "The Verge", URL: "https://www.theverge.com/search?q={query}", Category: "news"},
	{Shortcut: "wired", Name: "Wired", URL: "https://www.wired.com/search/?q={query}", Category: "news"},
	{Shortcut: "arstechnica", Name: "Ars Technica", URL: "https://arstechnica.com/search/?q={query}", Category: "news", Aliases: []string{"ars"}},
	{Shortcut: "engadget", Name: "Engadget", URL: "https://www.engadget.com/search/?search={query}", Category: "news"},
	{Shortcut: "cnet", Name: "CNET", URL: "https://www.cnet.com/search/?query={query}", Category: "news"},
	{Shortcut: "zdnet", Name: "ZDNet", URL: "https://www.zdnet.com/search/?q={query}", Category: "news"},
	{Shortcut: "venturebeat", Name: "VentureBeat", URL: "https://venturebeat.com/?s={query}", Category: "news", Aliases: []string{"vb"}},
	{Shortcut: "hackernoon", Name: "HackerNoon", URL: "https://hackernoon.com/search?query={query}", Category: "news"},
	{Shortcut: "bloomberg", Name: "Bloomberg", URL: "https://www.bloomberg.com/search?query={query}", Category: "news"},
	{Shortcut: "ft", Name: "Financial Times", URL: "https://www.ft.com/search?q={query}", Category: "news"},
	{Shortcut: "wsj", Name: "Wall Street Journal", URL: "https://www.wsj.com/search?query={query}", Category: "news"},
	{Shortcut: "economist", Name: "The Economist", URL: "https://www.economist.com/search?q={query}", Category: "news"},
	{Shortcut: "forbes", Name: "Forbes", URL: "https://www.forbes.com/search/?q={query}", Category: "news"},
	{Shortcut: "businessinsider", Name: "Business Insider", URL: "https://www.businessinsider.com/s?q={query}", Category: "news", Aliases: []string{"bi"}},

	// ============================================================================
	// KNOWLEDGE & ENCYCLOPEDIA
	// ============================================================================
	{Shortcut: "w", Name: "Wikipedia", URL: "https://en.wikipedia.org/wiki/Special:Search?search={query}", Category: "knowledge", Aliases: []string{"wiki", "wikipedia"}},
	{Shortcut: "wd", Name: "Wikidata", URL: "https://www.wikidata.org/wiki/Special:Search?search={query}", Category: "knowledge", Aliases: []string{"wikidata"}},
	{Shortcut: "wt", Name: "Wiktionary", URL: "https://en.wiktionary.org/wiki/Special:Search?search={query}", Category: "knowledge", Aliases: []string{"wiktionary"}},
	{Shortcut: "wb", Name: "Wikibooks", URL: "https://en.wikibooks.org/wiki/Special:Search?search={query}", Category: "knowledge", Aliases: []string{"wikibooks"}},
	{Shortcut: "wq", Name: "Wikiquote", URL: "https://en.wikiquote.org/wiki/Special:Search?search={query}", Category: "knowledge", Aliases: []string{"wikiquote"}},
	{Shortcut: "ws", Name: "Wikisource", URL: "https://en.wikisource.org/wiki/Special:Search?search={query}", Category: "knowledge", Aliases: []string{"wikisource"}},
	{Shortcut: "wn", Name: "Wikinews", URL: "https://en.wikinews.org/wiki/Special:Search?search={query}", Category: "knowledge", Aliases: []string{"wikinews"}},
	{Shortcut: "wv", Name: "Wikivoyage", URL: "https://en.wikivoyage.org/wiki/Special:Search?search={query}", Category: "knowledge", Aliases: []string{"wikivoyage"}},
	{Shortcut: "wa", Name: "Wolfram Alpha", URL: "https://www.wolframalpha.com/input/?i={query}", Category: "knowledge", Aliases: []string{"wolfram", "wolframalpha"}},
	{Shortcut: "britannica", Name: "Britannica", URL: "https://www.britannica.com/search?query={query}", Category: "knowledge"},
	{Shortcut: "quora", Name: "Quora", URL: "https://www.quora.com/search?q={query}", Category: "knowledge"},
	{Shortcut: "answers", Name: "Answers.com", URL: "https://www.answers.com/search?q={query}", Category: "knowledge"},
	{Shortcut: "howstuffworks", Name: "HowStuffWorks", URL: "https://www.howstuffworks.com/search.php?terms={query}", Category: "knowledge", Aliases: []string{"hsw"}},
	{Shortcut: "scholarpedia", Name: "Scholarpedia", URL: "http://www.scholarpedia.org/article/Special:Search?search={query}", Category: "knowledge"},
	{Shortcut: "citizendium", Name: "Citizendium", URL: "http://en.citizendium.org/wiki?search={query}", Category: "knowledge"},
	{Shortcut: "infoplease", Name: "Infoplease", URL: "https://www.infoplease.com/search/{query}", Category: "knowledge"},
	{Shortcut: "fandom", Name: "Fandom", URL: "https://www.fandom.com/?s={query}", Category: "knowledge"},
	{Shortcut: "tvtropes", Name: "TV Tropes", URL: "https://tvtropes.org/pmwiki/search_result.php?q={query}", Category: "knowledge"},

	// ============================================================================
	// SOCIAL MEDIA
	// ============================================================================
	{Shortcut: "tw", Name: "Twitter/X", URL: "https://twitter.com/search?q={query}", Category: "social", Aliases: []string{"twitter", "x"}},
	{Shortcut: "mast", Name: "Mastodon", URL: "https://mastodon.social/search?q={query}", Category: "social", Aliases: []string{"mastodon"}},
	{Shortcut: "rd", Name: "Reddit", URL: "https://www.reddit.com/search/?q={query}", Category: "social", Aliases: []string{"reddit"}},
	{Shortcut: "hn", Name: "Hacker News", URL: "https://hn.algolia.com/?q={query}", Category: "social", Aliases: []string{"hackernews"}},
	{Shortcut: "lb", Name: "Lobsters", URL: "https://lobste.rs/search?q={query}", Category: "social", Aliases: []string{"lobsters"}},
	{Shortcut: "fb", Name: "Facebook", URL: "https://www.facebook.com/search/top/?q={query}", Category: "social", Aliases: []string{"facebook"}},
	{Shortcut: "ig", Name: "Instagram", URL: "https://www.instagram.com/explore/tags/{query}", Category: "social", Aliases: []string{"instagram"}},
	{Shortcut: "linkedin", Name: "LinkedIn", URL: "https://www.linkedin.com/search/results/all/?keywords={query}", Category: "social", Aliases: []string{"li"}},
	{Shortcut: "tumblr", Name: "Tumblr", URL: "https://www.tumblr.com/search/{query}", Category: "social"},
	{Shortcut: "discord", Name: "Discord", URL: "https://discord.com/servers/search?query={query}", Category: "social"},
	{Shortcut: "slack", Name: "Slack", URL: "https://slack.com/apps/search?q={query}", Category: "social"},
	{Shortcut: "telegram", Name: "Telegram", URL: "https://t.me/s/{query}", Category: "social", Aliases: []string{"tg"}},
	{Shortcut: "medium", Name: "Medium", URL: "https://medium.com/search?q={query}", Category: "social"},
	{Shortcut: "substack", Name: "Substack", URL: "https://substack.com/search/{query}", Category: "social"},
	{Shortcut: "lemmy", Name: "Lemmy", URL: "https://lemmy.world/search?q={query}", Category: "social"},
	{Shortcut: "minds", Name: "Minds", URL: "https://www.minds.com/search?q={query}", Category: "social"},
	{Shortcut: "gab", Name: "Gab", URL: "https://gab.com/search?q={query}", Category: "social"},
	{Shortcut: "parler", Name: "Parler", URL: "https://parler.com/search?q={query}", Category: "social"},
	{Shortcut: "truthsocial", Name: "Truth Social", URL: "https://truthsocial.com/search?q={query}", Category: "social"},
	{Shortcut: "bluesky", Name: "Bluesky", URL: "https://bsky.app/search?q={query}", Category: "social", Aliases: []string{"bsky"}},
	{Shortcut: "threads", Name: "Threads", URL: "https://www.threads.net/search?q={query}", Category: "social"},
	{Shortcut: "snapchat", Name: "Snapchat", URL: "https://www.snapchat.com/search?q={query}", Category: "social", Aliases: []string{"snap"}},
	{Shortcut: "whatsapp", Name: "WhatsApp", URL: "https://www.whatsapp.com/?q={query}", Category: "social"},
	{Shortcut: "signal", Name: "Signal", URL: "https://signal.org/search?q={query}", Category: "social"},
	{Shortcut: "matrix", Name: "Matrix", URL: "https://matrix.to/#/{query}", Category: "social"},

	// ============================================================================
	// CODE & DEVELOPMENT
	// ============================================================================
	{Shortcut: "gh", Name: "GitHub", URL: "https://github.com/search?q={query}", Category: "code", Aliases: []string{"github"}},
	{Shortcut: "ghc", Name: "GitHub Code", URL: "https://github.com/search?type=code&q={query}", Category: "code"},
	{Shortcut: "ghr", Name: "GitHub Repos", URL: "https://github.com/search?type=repositories&q={query}", Category: "code"},
	{Shortcut: "ghu", Name: "GitHub Users", URL: "https://github.com/search?type=users&q={query}", Category: "code"},
	{Shortcut: "ghi", Name: "GitHub Issues", URL: "https://github.com/search?type=issues&q={query}", Category: "code"},
	{Shortcut: "ghd", Name: "GitHub Discussions", URL: "https://github.com/search?type=discussions&q={query}", Category: "code"},
	{Shortcut: "gist", Name: "GitHub Gist", URL: "https://gist.github.com/search?q={query}", Category: "code"},
	{Shortcut: "gl", Name: "GitLab", URL: "https://gitlab.com/search?search={query}", Category: "code", Aliases: []string{"gitlab"}},
	{Shortcut: "bb", Name: "Bitbucket", URL: "https://bitbucket.org/repo/all?name={query}", Category: "code", Aliases: []string{"bitbucket"}},
	{Shortcut: "sr", Name: "Sourcegraph", URL: "https://sourcegraph.com/search?q={query}", Category: "code", Aliases: []string{"sourcegraph"}},
	{Shortcut: "so", Name: "Stack Overflow", URL: "https://stackoverflow.com/search?q={query}", Category: "code", Aliases: []string{"stackoverflow"}},
	{Shortcut: "se", Name: "Stack Exchange", URL: "https://stackexchange.com/search?q={query}", Category: "code", Aliases: []string{"stackexchange"}},
	{Shortcut: "su", Name: "Super User", URL: "https://superuser.com/search?q={query}", Category: "code", Aliases: []string{"superuser"}},
	{Shortcut: "sf", Name: "Server Fault", URL: "https://serverfault.com/search?q={query}", Category: "code", Aliases: []string{"serverfault"}},
	{Shortcut: "au", Name: "Ask Ubuntu", URL: "https://askubuntu.com/search?q={query}", Category: "code", Aliases: []string{"askubuntu"}},
	{Shortcut: "unix", Name: "Unix & Linux", URL: "https://unix.stackexchange.com/search?q={query}", Category: "code"},
	{Shortcut: "npm", Name: "npm", URL: "https://www.npmjs.com/search?q={query}", Category: "code"},
	{Shortcut: "yarn", Name: "Yarn", URL: "https://yarnpkg.com/package?q={query}", Category: "code"},
	{Shortcut: "pypi", Name: "PyPI", URL: "https://pypi.org/search/?q={query}", Category: "code", Aliases: []string{"pip"}},
	{Shortcut: "crates", Name: "Crates.io", URL: "https://crates.io/search?q={query}", Category: "code", Aliases: []string{"cargo", "rust"}},
	{Shortcut: "gopkg", Name: "Go Packages", URL: "https://pkg.go.dev/search?q={query}", Category: "code", Aliases: []string{"go", "golang"}},
	{Shortcut: "hex", Name: "Hex.pm", URL: "https://hex.pm/packages?search={query}", Category: "code", Aliases: []string{"elixir", "erlang"}},
	{Shortcut: "rubygems", Name: "RubyGems", URL: "https://rubygems.org/search?query={query}", Category: "code", Aliases: []string{"gem", "ruby"}},
	{Shortcut: "nuget", Name: "NuGet", URL: "https://www.nuget.org/packages?q={query}", Category: "code", Aliases: []string{"dotnet"}},
	{Shortcut: "maven", Name: "Maven Central", URL: "https://search.maven.org/search?q={query}", Category: "code", Aliases: []string{"java"}},
	{Shortcut: "packagist", Name: "Packagist", URL: "https://packagist.org/search/?q={query}", Category: "code", Aliases: []string{"php", "composer"}},
	{Shortcut: "cpan", Name: "CPAN", URL: "https://metacpan.org/search?q={query}", Category: "code", Aliases: []string{"perl"}},
	{Shortcut: "cran", Name: "CRAN", URL: "https://cran.r-project.org/web/packages/available_packages_by_name.html#{query}", Category: "code", Aliases: []string{"r"}},
	{Shortcut: "cocoapods", Name: "CocoaPods", URL: "https://cocoapods.org/search?q={query}", Category: "code", Aliases: []string{"swift", "ios"}},
	{Shortcut: "pub", Name: "pub.dev", URL: "https://pub.dev/packages?q={query}", Category: "code", Aliases: []string{"dart", "flutter"}},
	{Shortcut: "haskell", Name: "Hackage", URL: "https://hackage.haskell.org/packages/search?terms={query}", Category: "code", Aliases: []string{"hackage"}},
	{Shortcut: "docker", Name: "Docker Hub", URL: "https://hub.docker.com/search?q={query}", Category: "code", Aliases: []string{"dockerhub"}},
	{Shortcut: "quay", Name: "Quay.io", URL: "https://quay.io/search?q={query}", Category: "code"},
	{Shortcut: "ghcr", Name: "GitHub Container Registry", URL: "https://github.com/orgs/community/packages?q={query}", Category: "code"},
	{Shortcut: "helm", Name: "Helm Hub", URL: "https://artifacthub.io/packages/search?ts_query_web={query}", Category: "code"},
	{Shortcut: "terraform", Name: "Terraform Registry", URL: "https://registry.terraform.io/search/modules?q={query}", Category: "code", Aliases: []string{"tf"}},
	{Shortcut: "ansible", Name: "Ansible Galaxy", URL: "https://galaxy.ansible.com/search?keywords={query}", Category: "code"},
	{Shortcut: "mdn", Name: "MDN Web Docs", URL: "https://developer.mozilla.org/en-US/search?q={query}", Category: "code", Aliases: []string{"mozilla"}},
	{Shortcut: "can", Name: "Can I Use", URL: "https://caniuse.com/?search={query}", Category: "code", Aliases: []string{"caniuse"}},
	{Shortcut: "w3schools", Name: "W3Schools", URL: "https://www.w3schools.com/search/search.asp?q={query}", Category: "code", Aliases: []string{"w3s"}},
	{Shortcut: "devdocs", Name: "DevDocs", URL: "https://devdocs.io/#q={query}", Category: "code"},
	{Shortcut: "codepen", Name: "CodePen", URL: "https://codepen.io/search/pens?q={query}", Category: "code"},
	{Shortcut: "jsfiddle", Name: "JSFiddle", URL: "https://jsfiddle.net/search/?q={query}", Category: "code"},
	{Shortcut: "codesandbox", Name: "CodeSandbox", URL: "https://codesandbox.io/search?query={query}", Category: "code", Aliases: []string{"csb"}},
	{Shortcut: "replit", Name: "Replit", URL: "https://replit.com/search?q={query}", Category: "code"},
	{Shortcut: "glitch", Name: "Glitch", URL: "https://glitch.com/search?q={query}", Category: "code"},
	{Shortcut: "leetcode", Name: "LeetCode", URL: "https://leetcode.com/problemset/all/?search={query}", Category: "code", Aliases: []string{"lc"}},
	{Shortcut: "hackerrank", Name: "HackerRank", URL: "https://www.hackerrank.com/contests?query={query}", Category: "code", Aliases: []string{"hr"}},
	{Shortcut: "codewars", Name: "Codewars", URL: "https://www.codewars.com/kata/search/{query}", Category: "code"},
	{Shortcut: "exercism", Name: "Exercism", URL: "https://exercism.org/tracks?criteria={query}", Category: "code"},
	{Shortcut: "rosetta", Name: "Rosetta Code", URL: "https://rosettacode.org/w/index.php?search={query}", Category: "code"},
	{Shortcut: "regex101", Name: "Regex101", URL: "https://regex101.com/library?search={query}", Category: "code"},
	{Shortcut: "explainshell", Name: "ExplainShell", URL: "https://explainshell.com/explain?cmd={query}", Category: "code"},
	{Shortcut: "tldr", Name: "TLDR Pages", URL: "https://tldr.inbrowser.app/search/{query}", Category: "code"},
	{Shortcut: "devhints", Name: "Devhints", URL: "https://devhints.io/{query}", Category: "code"},
	{Shortcut: "cheatography", Name: "Cheatography", URL: "https://cheatography.com/explore/search/?q={query}", Category: "code"},

	// ============================================================================
	// SHOPPING
	// ============================================================================
	{Shortcut: "az", Name: "Amazon", URL: "https://www.amazon.com/s?k={query}", Category: "shopping", Aliases: []string{"amazon"}},
	{Shortcut: "azuk", Name: "Amazon UK", URL: "https://www.amazon.co.uk/s?k={query}", Category: "shopping"},
	{Shortcut: "azde", Name: "Amazon Germany", URL: "https://www.amazon.de/s?k={query}", Category: "shopping"},
	{Shortcut: "azjp", Name: "Amazon Japan", URL: "https://www.amazon.co.jp/s?k={query}", Category: "shopping"},
	{Shortcut: "eb", Name: "eBay", URL: "https://www.ebay.com/sch/i.html?_nkw={query}", Category: "shopping", Aliases: []string{"ebay"}},
	{Shortcut: "aliexpress", Name: "AliExpress", URL: "https://www.aliexpress.com/wholesale?SearchText={query}", Category: "shopping", Aliases: []string{"ali"}},
	{Shortcut: "alibaba", Name: "Alibaba", URL: "https://www.alibaba.com/trade/search?SearchText={query}", Category: "shopping"},
	{Shortcut: "walmart", Name: "Walmart", URL: "https://www.walmart.com/search?q={query}", Category: "shopping"},
	{Shortcut: "target", Name: "Target", URL: "https://www.target.com/s?searchTerm={query}", Category: "shopping"},
	{Shortcut: "bestbuy", Name: "Best Buy", URL: "https://www.bestbuy.com/site/searchpage.jsp?st={query}", Category: "shopping", Aliases: []string{"bb"}},
	{Shortcut: "newegg", Name: "Newegg", URL: "https://www.newegg.com/p/pl?d={query}", Category: "shopping"},
	{Shortcut: "etsy", Name: "Etsy", URL: "https://www.etsy.com/search?q={query}", Category: "shopping"},
	{Shortcut: "wish", Name: "Wish", URL: "https://www.wish.com/search/{query}", Category: "shopping"},
	{Shortcut: "shopify", Name: "Shopify", URL: "https://www.shopify.com/search?q={query}", Category: "shopping"},
	{Shortcut: "camelcamelcamel", Name: "CamelCamelCamel", URL: "https://camelcamelcamel.com/search?sq={query}", Category: "shopping", Aliases: []string{"ccc"}},
	{Shortcut: "keepa", Name: "Keepa", URL: "https://keepa.com/#!search/{query}", Category: "shopping"},
	{Shortcut: "pricespy", Name: "PriceSpy", URL: "https://pricespy.co.uk/search?search={query}", Category: "shopping"},
	{Shortcut: "slickdeals", Name: "Slickdeals", URL: "https://slickdeals.net/newsearch.php?q={query}", Category: "shopping"},
	{Shortcut: "rakuten", Name: "Rakuten", URL: "https://search.rakuten.co.jp/search/mall/{query}/", Category: "shopping"},
	{Shortcut: "mercari", Name: "Mercari", URL: "https://www.mercari.com/search/?keyword={query}", Category: "shopping"},
	{Shortcut: "poshmark", Name: "Poshmark", URL: "https://poshmark.com/search?query={query}", Category: "shopping"},
	{Shortcut: "thriftbooks", Name: "ThriftBooks", URL: "https://www.thriftbooks.com/browse/?b.search={query}", Category: "shopping"},
	{Shortcut: "bookfinder", Name: "BookFinder", URL: "https://www.bookfinder.com/search/?keywords={query}", Category: "shopping"},

	// ============================================================================
	// FILES & TORRENTS
	// ============================================================================
	{Shortcut: "archive", Name: "Internet Archive", URL: "https://archive.org/search.php?query={query}", Category: "files", Aliases: []string{"ia"}},
	{Shortcut: "1337x", Name: "1337x", URL: "https://1337x.to/search/{query}/1/", Category: "files"},
	{Shortcut: "rarbg", Name: "RARBG", URL: "https://rargb.to/search/?search={query}", Category: "files"},
	{Shortcut: "nyaa", Name: "Nyaa", URL: "https://nyaa.si/?q={query}", Category: "files"},
	{Shortcut: "libgen", Name: "Library Genesis", URL: "https://libgen.is/search.php?req={query}", Category: "files", Aliases: []string{"lg"}},
	{Shortcut: "zlibrary", Name: "Z-Library", URL: "https://z-lib.org/s/{query}", Category: "files", Aliases: []string{"zlib"}},
	{Shortcut: "annas", Name: "Anna's Archive", URL: "https://annas-archive.org/search?q={query}", Category: "files"},
	{Shortcut: "sci-hub", Name: "Sci-Hub", URL: "https://sci-hub.se/{query}", Category: "files", Aliases: []string{"scihub"}},
	{Shortcut: "pdfdrive", Name: "PDF Drive", URL: "https://www.pdfdrive.com/search?q={query}", Category: "files"},
	{Shortcut: "openlib", Name: "Open Library", URL: "https://openlibrary.org/search?q={query}", Category: "files", Aliases: []string{"openlibrary"}},
	{Shortcut: "gutenberg", Name: "Project Gutenberg", URL: "https://www.gutenberg.org/ebooks/search/?query={query}", Category: "files"},
	{Shortcut: "standardebooks", Name: "Standard Ebooks", URL: "https://standardebooks.org/ebooks?query={query}", Category: "files"},
	{Shortcut: "audiobookbay", Name: "AudioBook Bay", URL: "https://audiobookbay.is/?s={query}", Category: "files", Aliases: []string{"abb"}},

	// ============================================================================
	// MUSIC
	// ============================================================================
	{Shortcut: "spot", Name: "Spotify", URL: "https://open.spotify.com/search/{query}", Category: "music", Aliases: []string{"spotify"}},
	{Shortcut: "apple", Name: "Apple Music", URL: "https://music.apple.com/search?term={query}", Category: "music", Aliases: []string{"applemusic"}},
	{Shortcut: "ytm", Name: "YouTube Music", URL: "https://music.youtube.com/search?q={query}", Category: "music", Aliases: []string{"youtubemusic"}},
	{Shortcut: "sc", Name: "SoundCloud", URL: "https://soundcloud.com/search?q={query}", Category: "music", Aliases: []string{"soundcloud"}},
	{Shortcut: "bc", Name: "Bandcamp", URL: "https://bandcamp.com/search?q={query}", Category: "music", Aliases: []string{"bandcamp"}},
	{Shortcut: "lastfm", Name: "Last.fm", URL: "https://www.last.fm/search?q={query}", Category: "music"},
	{Shortcut: "discogs", Name: "Discogs", URL: "https://www.discogs.com/search/?q={query}", Category: "music"},
	{Shortcut: "allmusic", Name: "AllMusic", URL: "https://www.allmusic.com/search/all/{query}", Category: "music"},
	{Shortcut: "lyrics", Name: "Genius Lyrics", URL: "https://genius.com/search?q={query}", Category: "music", Aliases: []string{"genius"}},
	{Shortcut: "azlyrics", Name: "AZLyrics", URL: "https://search.azlyrics.com/search.php?q={query}", Category: "music"},
	{Shortcut: "musixmatch", Name: "Musixmatch", URL: "https://www.musixmatch.com/search/{query}", Category: "music"},
	{Shortcut: "songmeanings", Name: "SongMeanings", URL: "https://songmeanings.com/query/?query={query}", Category: "music"},
	{Shortcut: "setlistfm", Name: "Setlist.fm", URL: "https://www.setlist.fm/search?query={query}", Category: "music"},
	{Shortcut: "songkick", Name: "Songkick", URL: "https://www.songkick.com/search?query={query}", Category: "music"},
	{Shortcut: "rateyourmusic", Name: "Rate Your Music", URL: "https://rateyourmusic.com/search?searchterm={query}", Category: "music", Aliases: []string{"rym"}},
	{Shortcut: "musicbrainz", Name: "MusicBrainz", URL: "https://musicbrainz.org/search?query={query}", Category: "music"},
	{Shortcut: "deezer", Name: "Deezer", URL: "https://www.deezer.com/search/{query}", Category: "music"},
	{Shortcut: "tidal", Name: "Tidal", URL: "https://tidal.com/search?q={query}", Category: "music"},
	{Shortcut: "audiomack", Name: "Audiomack", URL: "https://audiomack.com/search?q={query}", Category: "music"},
	{Shortcut: "mixcloud", Name: "Mixcloud", URL: "https://www.mixcloud.com/search/?q={query}", Category: "music"},
	{Shortcut: "hearthis", Name: "hearthis.at", URL: "https://hearthis.at/search/{query}/", Category: "music"},

	// ============================================================================
	// SCIENCE & ACADEMIC
	// ============================================================================
	{Shortcut: "scholar", Name: "Google Scholar", URL: "https://scholar.google.com/scholar?q={query}", Category: "science", Aliases: []string{"gs", "googlescholar"}},
	{Shortcut: "arxiv", Name: "arXiv", URL: "https://arxiv.org/search/?query={query}", Category: "science"},
	{Shortcut: "pubmed", Name: "PubMed", URL: "https://pubmed.ncbi.nlm.nih.gov/?term={query}", Category: "science"},
	{Shortcut: "semanticscholar", Name: "Semantic Scholar", URL: "https://www.semanticscholar.org/search?q={query}", Category: "science", Aliases: []string{"s2"}},
	{Shortcut: "researchgate", Name: "ResearchGate", URL: "https://www.researchgate.net/search?q={query}", Category: "science", Aliases: []string{"rg"}},
	{Shortcut: "academia", Name: "Academia.edu", URL: "https://www.academia.edu/search?q={query}", Category: "science"},
	{Shortcut: "jstor", Name: "JSTOR", URL: "https://www.jstor.org/action/doBasicSearch?Query={query}", Category: "science"},
	{Shortcut: "ieee", Name: "IEEE Xplore", URL: "https://ieeexplore.ieee.org/search/searchresult.jsp?queryText={query}", Category: "science"},
	{Shortcut: "acm", Name: "ACM Digital Library", URL: "https://dl.acm.org/action/doSearch?AllField={query}", Category: "science"},
	{Shortcut: "springerlink", Name: "SpringerLink", URL: "https://link.springer.com/search?query={query}", Category: "science", Aliases: []string{"springer"}},
	{Shortcut: "nature", Name: "Nature", URL: "https://www.nature.com/search?q={query}", Category: "science"},
	{Shortcut: "science", Name: "Science", URL: "https://www.science.org/action/doSearch?AllField={query}", Category: "science"},
	{Shortcut: "plos", Name: "PLOS ONE", URL: "https://journals.plos.org/plosone/search?q={query}", Category: "science"},
	{Shortcut: "biorxiv", Name: "bioRxiv", URL: "https://www.biorxiv.org/search/{query}", Category: "science"},
	{Shortcut: "medrxiv", Name: "medRxiv", URL: "https://www.medrxiv.org/search/{query}", Category: "science"},
	{Shortcut: "chemrxiv", Name: "ChemRxiv", URL: "https://chemrxiv.org/engage/chemrxiv/search-dashboard?text={query}", Category: "science"},
	{Shortcut: "ssrn", Name: "SSRN", URL: "https://papers.ssrn.com/sol3/results.cfm?RequestTimeout=50000000&txtKey_Words={query}", Category: "science"},
	{Shortcut: "philpapers", Name: "PhilPapers", URL: "https://philpapers.org/s/{query}", Category: "science"},
	{Shortcut: "doaj", Name: "DOAJ", URL: "https://doaj.org/search/articles?ref=homepage-box&source={query}", Category: "science"},
	{Shortcut: "core", Name: "CORE", URL: "https://core.ac.uk/search?q={query}", Category: "science"},
	{Shortcut: "base", Name: "BASE", URL: "https://www.base-search.net/Search/Results?lookfor={query}", Category: "science"},
	{Shortcut: "dimensions", Name: "Dimensions", URL: "https://app.dimensions.ai/discover/publication?search_mode=content&search_text={query}", Category: "science"},
	{Shortcut: "lens", Name: "The Lens", URL: "https://www.lens.org/lens/search/scholar/list?q={query}", Category: "science"},
	{Shortcut: "orcid", Name: "ORCID", URL: "https://orcid.org/orcid-search/search?searchQuery={query}", Category: "science"},
	{Shortcut: "crossref", Name: "Crossref", URL: "https://search.crossref.org/?q={query}", Category: "science"},
	{Shortcut: "doi", Name: "DOI Resolver", URL: "https://doi.org/{query}", Category: "science"},
	{Shortcut: "nasa", Name: "NASA", URL: "https://www.nasa.gov/search/?q={query}", Category: "science"},
	{Shortcut: "esa", Name: "ESA", URL: "https://www.esa.int/esearch?q={query}", Category: "science"},
	{Shortcut: "ncbi", Name: "NCBI", URL: "https://www.ncbi.nlm.nih.gov/search/all/?term={query}", Category: "science"},

	// ============================================================================
	// TRANSLATION & DICTIONARY
	// ============================================================================
	{Shortcut: "gt", Name: "Google Translate", URL: "https://translate.google.com/?sl=auto&tl=en&text={query}", Category: "translate", Aliases: []string{"translate", "googletranslate"}},
	{Shortcut: "deepl", Name: "DeepL", URL: "https://www.deepl.com/translator#auto/en/{query}", Category: "translate"},
	{Shortcut: "bing", Name: "Bing Translator", URL: "https://www.bing.com/translator/?text={query}", Category: "translate", Aliases: []string{"bingtranslate"}},
	{Shortcut: "reverso", Name: "Reverso", URL: "https://www.reverso.net/text-translation#sl=auto&tl=en&text={query}", Category: "translate"},
	{Shortcut: "linguee", Name: "Linguee", URL: "https://www.linguee.com/english-german/search?source=auto&query={query}", Category: "translate"},
	{Shortcut: "dict", Name: "Dictionary.com", URL: "https://www.dictionary.com/browse/{query}", Category: "translate", Aliases: []string{"dictionary"}},
	{Shortcut: "thesaurus", Name: "Thesaurus.com", URL: "https://www.thesaurus.com/browse/{query}", Category: "translate"},
	{Shortcut: "mw", Name: "Merriam-Webster", URL: "https://www.merriam-webster.com/dictionary/{query}", Category: "translate", Aliases: []string{"merriamwebster"}},
	{Shortcut: "oxford", Name: "Oxford Dictionary", URL: "https://www.oxfordlearnersdictionaries.com/search/english/?q={query}", Category: "translate"},
	{Shortcut: "cambridge", Name: "Cambridge Dictionary", URL: "https://dictionary.cambridge.org/search/english/?q={query}", Category: "translate"},
	{Shortcut: "collins", Name: "Collins Dictionary", URL: "https://www.collinsdictionary.com/search/?dictCode=english&q={query}", Category: "translate"},
	{Shortcut: "longman", Name: "Longman Dictionary", URL: "https://www.ldoceonline.com/search/english/direct/?q={query}", Category: "translate"},
	{Shortcut: "macmillan", Name: "Macmillan Dictionary", URL: "https://www.macmillandictionary.com/search/british/?q={query}", Category: "translate"},
	{Shortcut: "ud", Name: "Urban Dictionary", URL: "https://www.urbandictionary.com/define.php?term={query}", Category: "translate", Aliases: []string{"urban", "urbandictionary"}},
	{Shortcut: "etymonline", Name: "Etymonline", URL: "https://www.etymonline.com/search?q={query}", Category: "translate", Aliases: []string{"etymology"}},
	{Shortcut: "wordnik", Name: "Wordnik", URL: "https://www.wordnik.com/words/{query}", Category: "translate"},
	{Shortcut: "forvo", Name: "Forvo", URL: "https://forvo.com/search/{query}/", Category: "translate"},
	{Shortcut: "wordreference", Name: "WordReference", URL: "https://www.wordreference.com/definition/{query}", Category: "translate", Aliases: []string{"wr"}},
	{Shortcut: "leo", Name: "LEO Dictionary", URL: "https://dict.leo.org/english-german/{query}", Category: "translate"},
	{Shortcut: "pons", Name: "PONS", URL: "https://en.pons.com/translate?q={query}", Category: "translate"},
	{Shortcut: "jisho", Name: "Jisho", URL: "https://jisho.org/search/{query}", Category: "translate", Aliases: []string{"japanese"}},
	{Shortcut: "tangorin", Name: "Tangorin", URL: "https://tangorin.com/words?search={query}", Category: "translate"},
	{Shortcut: "naver", Name: "Naver Dictionary", URL: "https://dict.naver.com/search.nhn?query={query}", Category: "translate", Aliases: []string{"korean"}},
	{Shortcut: "pleco", Name: "Pleco", URL: "https://www.pleco.com/search/?q={query}", Category: "translate", Aliases: []string{"chinese"}},
	{Shortcut: "mdbg", Name: "MDBG Chinese", URL: "https://www.mdbg.net/chinese/dictionary?page=worddict&wdrst=0&wdqb={query}", Category: "translate"},

	// ============================================================================
	// PRIVACY & SECURITY
	// ============================================================================
	{Shortcut: "wbm", Name: "Wayback Machine", URL: "https://web.archive.org/web/*/{query}", Category: "privacy", Aliases: []string{"wayback"}},
	{Shortcut: "haveibeenpwned", Name: "Have I Been Pwned", URL: "https://haveibeenpwned.com/unifiedsearch/{query}", Category: "privacy", Aliases: []string{"hibp", "pwned"}},
	{Shortcut: "dehashed", Name: "DeHashed", URL: "https://www.dehashed.com/search?query={query}", Category: "privacy"},
	{Shortcut: "virustotal", Name: "VirusTotal", URL: "https://www.virustotal.com/gui/search/{query}", Category: "privacy", Aliases: []string{"vt"}},
	{Shortcut: "shodan", Name: "Shodan", URL: "https://www.shodan.io/search?query={query}", Category: "privacy"},
	{Shortcut: "censys", Name: "Censys", URL: "https://search.censys.io/search?resource=hosts&q={query}", Category: "privacy"},
	{Shortcut: "crt", Name: "crt.sh", URL: "https://crt.sh/?q={query}", Category: "privacy", Aliases: []string{"crtsh"}},
	{Shortcut: "dnsdumpster", Name: "DNSDumpster", URL: "https://dnsdumpster.com/?search={query}", Category: "privacy"},
	{Shortcut: "securitytrails", Name: "SecurityTrails", URL: "https://securitytrails.com/domain/{query}/dns", Category: "privacy"},
	{Shortcut: "whois", Name: "WHOIS", URL: "https://www.whois.com/whois/{query}", Category: "privacy"},
	{Shortcut: "ipinfo", Name: "IPinfo", URL: "https://ipinfo.io/{query}", Category: "privacy"},
	{Shortcut: "abuseipdb", Name: "AbuseIPDB", URL: "https://www.abuseipdb.com/check/{query}", Category: "privacy"},
	{Shortcut: "urlscan", Name: "urlscan.io", URL: "https://urlscan.io/search/#{query}", Category: "privacy"},
	{Shortcut: "httpstatus", Name: "HTTP Status", URL: "https://httpstatus.io/?url={query}", Category: "privacy"},
	{Shortcut: "ssltest", Name: "SSL Labs", URL: "https://www.ssllabs.com/ssltest/analyze.html?d={query}", Category: "privacy", Aliases: []string{"ssllabs"}},
	{Shortcut: "securityheaders", Name: "Security Headers", URL: "https://securityheaders.com/?q={query}", Category: "privacy"},
	{Shortcut: "builtwith", Name: "BuiltWith", URL: "https://builtwith.com/{query}", Category: "privacy"},
	{Shortcut: "wappalyzer", Name: "Wappalyzer", URL: "https://www.wappalyzer.com/lookup/{query}", Category: "privacy"},
	{Shortcut: "downforeveryoneorjustme", Name: "Down For Everyone", URL: "https://downforeveryoneorjustme.com/{query}", Category: "privacy", Aliases: []string{"isitdown", "down"}},

	// ============================================================================
	// MOVIES & TV
	// ============================================================================
	{Shortcut: "imdb", Name: "IMDb", URL: "https://www.imdb.com/find?q={query}", Category: "movies"},
	{Shortcut: "rt", Name: "Rotten Tomatoes", URL: "https://www.rottentomatoes.com/search?search={query}", Category: "movies", Aliases: []string{"rottentomatoes"}},
	{Shortcut: "metacritic", Name: "Metacritic", URL: "https://www.metacritic.com/search/{query}/", Category: "movies", Aliases: []string{"mc"}},
	{Shortcut: "letterboxd", Name: "Letterboxd", URL: "https://letterboxd.com/search/{query}/", Category: "movies"},
	{Shortcut: "tmdb", Name: "The Movie Database", URL: "https://www.themoviedb.org/search?query={query}", Category: "movies", Aliases: []string{"themoviedb"}},
	{Shortcut: "trakt", Name: "Trakt", URL: "https://trakt.tv/search?query={query}", Category: "movies"},
	{Shortcut: "justwatch", Name: "JustWatch", URL: "https://www.justwatch.com/us/search?q={query}", Category: "movies"},
	{Shortcut: "reelgood", Name: "Reelgood", URL: "https://reelgood.com/search?q={query}", Category: "movies"},
	{Shortcut: "tvdb", Name: "TheTVDB", URL: "https://thetvdb.com/search?query={query}", Category: "movies"},
	{Shortcut: "tvmaze", Name: "TVmaze", URL: "https://www.tvmaze.com/search?q={query}", Category: "movies"},
	{Shortcut: "episodecalendar", Name: "Episode Calendar", URL: "https://episodecalendar.com/search?q={query}", Category: "movies"},
	{Shortcut: "netflix", Name: "Netflix", URL: "https://www.netflix.com/search?q={query}", Category: "movies"},
	{Shortcut: "primevideo", Name: "Prime Video", URL: "https://www.amazon.com/s?i=instant-video&k={query}", Category: "movies", Aliases: []string{"amazonprime"}},
	{Shortcut: "hulu", Name: "Hulu", URL: "https://www.hulu.com/search?q={query}", Category: "movies"},
	{Shortcut: "disneyplus", Name: "Disney+", URL: "https://www.disneyplus.com/search?q={query}", Category: "movies", Aliases: []string{"disney"}},
	{Shortcut: "hbomax", Name: "Max", URL: "https://www.max.com/search?q={query}", Category: "movies", Aliases: []string{"max"}},
	{Shortcut: "peacock", Name: "Peacock", URL: "https://www.peacocktv.com/search?query={query}", Category: "movies"},
	{Shortcut: "paramount", Name: "Paramount+", URL: "https://www.paramountplus.com/search/?q={query}", Category: "movies", Aliases: []string{"paramountplus"}},

	// ============================================================================
	// GAMES
	// ============================================================================
	{Shortcut: "steam", Name: "Steam", URL: "https://store.steampowered.com/search/?term={query}", Category: "games"},
	{Shortcut: "gog", Name: "GOG", URL: "https://www.gog.com/games?query={query}", Category: "games"},
	{Shortcut: "epicgames", Name: "Epic Games", URL: "https://store.epicgames.com/en-US/browse?q={query}", Category: "games", Aliases: []string{"epic"}},
	{Shortcut: "itch", Name: "itch.io", URL: "https://itch.io/search?q={query}", Category: "games"},
	{Shortcut: "humble", Name: "Humble Bundle", URL: "https://www.humblebundle.com/store/search?search={query}", Category: "games", Aliases: []string{"humblebundle"}},
	{Shortcut: "isthereanydeal", Name: "IsThereAnyDeal", URL: "https://isthereanydeal.com/search/?q={query}", Category: "games", Aliases: []string{"itad"}},
	{Shortcut: "gg", Name: "GG.deals", URL: "https://gg.deals/games/?title={query}", Category: "games"},
	{Shortcut: "pcgamingwiki", Name: "PCGamingWiki", URL: "https://www.pcgamingwiki.com/w/index.php?search={query}", Category: "games"},
	{Shortcut: "howlongtobeat", Name: "HowLongToBeat", URL: "https://howlongtobeat.com/?q={query}", Category: "games", Aliases: []string{"hltb"}},
	{Shortcut: "igdb", Name: "IGDB", URL: "https://www.igdb.com/search?type=1&q={query}", Category: "games"},
	{Shortcut: "rawg", Name: "RAWG", URL: "https://rawg.io/search?query={query}", Category: "games"},
	{Shortcut: "mobygames", Name: "MobyGames", URL: "https://www.mobygames.com/search/?q={query}", Category: "games"},
	{Shortcut: "giantbomb", Name: "Giant Bomb", URL: "https://www.giantbomb.com/search/?q={query}", Category: "games"},
	{Shortcut: "gamefaqs", Name: "GameFAQs", URL: "https://gamefaqs.gamespot.com/search?game={query}", Category: "games"},
	{Shortcut: "speedrun", Name: "Speedrun.com", URL: "https://www.speedrun.com/search?q={query}", Category: "games"},
	{Shortcut: "strategywiki", Name: "StrategyWiki", URL: "https://strategywiki.org/w/index.php?search={query}", Category: "games"},
	{Shortcut: "steamdb", Name: "SteamDB", URL: "https://steamdb.info/search/?q={query}", Category: "games"},
	{Shortcut: "protondb", Name: "ProtonDB", URL: "https://www.protondb.com/search?q={query}", Category: "games"},
	{Shortcut: "nintendolife", Name: "Nintendo Life", URL: "https://www.nintendolife.com/search?q={query}", Category: "games"},
	{Shortcut: "playstation", Name: "PlayStation Store", URL: "https://store.playstation.com/search/{query}", Category: "games", Aliases: []string{"ps"}},
	{Shortcut: "xbox", Name: "Xbox Store", URL: "https://www.xbox.com/en-US/Search/Results?q={query}", Category: "games"},

	// ============================================================================
	// BOOKS & READING
	// ============================================================================
	{Shortcut: "goodreads", Name: "Goodreads", URL: "https://www.goodreads.com/search?q={query}", Category: "books", Aliases: []string{"gr"}},
	{Shortcut: "storygraph", Name: "StoryGraph", URL: "https://app.thestorygraph.com/browse?search_term={query}", Category: "books"},
	{Shortcut: "bookdepository", Name: "Book Depository", URL: "https://www.bookdepository.com/search?searchTerm={query}", Category: "books"},
	{Shortcut: "worldcat", Name: "WorldCat", URL: "https://www.worldcat.org/search?q={query}", Category: "books"},
	{Shortcut: "googlebooks", Name: "Google Books", URL: "https://books.google.com/books?q={query}", Category: "books", Aliases: []string{"gbooks"}},
	{Shortcut: "overdrive", Name: "OverDrive", URL: "https://www.overdrive.com/search?q={query}", Category: "books"},
	{Shortcut: "libby", Name: "Libby", URL: "https://libbyapp.com/search/{query}", Category: "books"},
	{Shortcut: "audible", Name: "Audible", URL: "https://www.audible.com/search?keywords={query}", Category: "books"},
	{Shortcut: "kindle", Name: "Kindle Store", URL: "https://www.amazon.com/s?i=digital-text&k={query}", Category: "books"},
	{Shortcut: "kobo", Name: "Kobo", URL: "https://www.kobo.com/search?query={query}", Category: "books"},
	{Shortcut: "barnesandnoble", Name: "Barnes & Noble", URL: "https://www.barnesandnoble.com/s/{query}", Category: "books", Aliases: []string{"bn"}},
	{Shortcut: "bookshop", Name: "Bookshop.org", URL: "https://bookshop.org/search?keywords={query}", Category: "books"},
	{Shortcut: "isfdb", Name: "ISFDB", URL: "https://www.isfdb.org/cgi-bin/se.cgi?arg={query}", Category: "books"},
	{Shortcut: "fantasticfiction", Name: "Fantastic Fiction", URL: "https://www.fantasticfiction.com/search/?searchfor=author&keywords={query}", Category: "books"},

	// ============================================================================
	// JOBS & CAREER
	// ============================================================================
	{Shortcut: "indeed", Name: "Indeed", URL: "https://www.indeed.com/jobs?q={query}", Category: "jobs"},
	{Shortcut: "glassdoor", Name: "Glassdoor", URL: "https://www.glassdoor.com/Search/results.htm?keyword={query}", Category: "jobs"},
	{Shortcut: "monster", Name: "Monster", URL: "https://www.monster.com/jobs/search?q={query}", Category: "jobs"},
	{Shortcut: "ziprecruiter", Name: "ZipRecruiter", URL: "https://www.ziprecruiter.com/jobs-search?search={query}", Category: "jobs"},
	{Shortcut: "careerbuilder", Name: "CareerBuilder", URL: "https://www.careerbuilder.com/jobs?keywords={query}", Category: "jobs"},
	{Shortcut: "simplyhired", Name: "SimplyHired", URL: "https://www.simplyhired.com/search?q={query}", Category: "jobs"},
	{Shortcut: "dice", Name: "Dice", URL: "https://www.dice.com/jobs?q={query}", Category: "jobs"},
	{Shortcut: "wellfound", Name: "Wellfound", URL: "https://wellfound.com/search?q={query}", Category: "jobs", Aliases: []string{"angellist"}},
	{Shortcut: "wwr", Name: "We Work Remotely", URL: "https://weworkremotely.com/remote-jobs/search?term={query}", Category: "jobs"},
	{Shortcut: "remoteok", Name: "Remote OK", URL: "https://remoteok.com/remote-{query}-jobs", Category: "jobs"},
	{Shortcut: "flexjobs", Name: "FlexJobs", URL: "https://www.flexjobs.com/search?search={query}", Category: "jobs"},
	{Shortcut: "ycombinator", Name: "Y Combinator Jobs", URL: "https://www.ycombinator.com/jobs?query={query}", Category: "jobs", Aliases: []string{"yc"}},
	{Shortcut: "levels", Name: "Levels.fyi", URL: "https://www.levels.fyi/companies/{query}", Category: "jobs"},
	{Shortcut: "crunchbase", Name: "Crunchbase", URL: "https://www.crunchbase.com/textsearch?q={query}", Category: "jobs"},

	// ============================================================================
	// FOOD & RECIPES
	// ============================================================================
	{Shortcut: "allrecipes", Name: "Allrecipes", URL: "https://www.allrecipes.com/search?q={query}", Category: "food"},
	{Shortcut: "foodnetwork", Name: "Food Network", URL: "https://www.foodnetwork.com/search/{query}-", Category: "food"},
	{Shortcut: "epicurious", Name: "Epicurious", URL: "https://www.epicurious.com/search/{query}", Category: "food"},
	{Shortcut: "seriouseats", Name: "Serious Eats", URL: "https://www.seriouseats.com/search?q={query}", Category: "food"},
	{Shortcut: "bonappetit", Name: "Bon Appetit", URL: "https://www.bonappetit.com/search?q={query}", Category: "food"},
	{Shortcut: "tasty", Name: "Tasty", URL: "https://tasty.co/search?q={query}", Category: "food"},
	{Shortcut: "yummly", Name: "Yummly", URL: "https://www.yummly.com/recipes?q={query}", Category: "food"},
	{Shortcut: "cookpad", Name: "Cookpad", URL: "https://cookpad.com/search/{query}", Category: "food"},
	{Shortcut: "foodcom", Name: "Food.com", URL: "https://www.food.com/search/{query}", Category: "food"},
	{Shortcut: "delish", Name: "Delish", URL: "https://www.delish.com/search/?q={query}", Category: "food"},
	{Shortcut: "simplyrecipes", Name: "Simply Recipes", URL: "https://www.simplyrecipes.com/?s={query}", Category: "food"},
	{Shortcut: "budgetbytes", Name: "Budget Bytes", URL: "https://www.budgetbytes.com/?s={query}", Category: "food"},
	{Shortcut: "doordash", Name: "DoorDash", URL: "https://www.doordash.com/search/store/{query}", Category: "food"},
	{Shortcut: "ubereats", Name: "Uber Eats", URL: "https://www.ubereats.com/search?q={query}", Category: "food"},
	{Shortcut: "grubhub", Name: "Grubhub", URL: "https://www.grubhub.com/search?queryText={query}", Category: "food"},

	// ============================================================================
	// SPORTS
	// ============================================================================
	{Shortcut: "espn", Name: "ESPN", URL: "https://www.espn.com/search/_/q/{query}", Category: "sports"},
	{Shortcut: "cbssports", Name: "CBS Sports", URL: "https://www.cbssports.com/search/{query}/", Category: "sports"},
	{Shortcut: "foxsports", Name: "Fox Sports", URL: "https://www.foxsports.com/search?q={query}", Category: "sports"},
	{Shortcut: "bleacherreport", Name: "Bleacher Report", URL: "https://bleacherreport.com/search?q={query}", Category: "sports", Aliases: []string{"br"}},
	{Shortcut: "theathletic", Name: "The Athletic", URL: "https://theathletic.com/search/?q={query}", Category: "sports"},
	{Shortcut: "nba", Name: "NBA", URL: "https://www.nba.com/search?q={query}", Category: "sports"},
	{Shortcut: "nfl", Name: "NFL", URL: "https://www.nfl.com/search?q={query}", Category: "sports"},
	{Shortcut: "mlb", Name: "MLB", URL: "https://www.mlb.com/search?q={query}", Category: "sports"},
	{Shortcut: "nhl", Name: "NHL", URL: "https://www.nhl.com/search?q={query}", Category: "sports"},
	{Shortcut: "mls", Name: "MLS", URL: "https://www.mlssoccer.com/search?q={query}", Category: "sports"},
	{Shortcut: "transfermarkt", Name: "Transfermarkt", URL: "https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query={query}", Category: "sports"},
	{Shortcut: "flashscore", Name: "Flashscore", URL: "https://www.flashscore.com/search/?q={query}", Category: "sports"},
	{Shortcut: "sofascore", Name: "SofaScore", URL: "https://www.sofascore.com/search?q={query}", Category: "sports"},

	// ============================================================================
	// TRAVEL
	// ============================================================================
	{Shortcut: "booking", Name: "Booking.com", URL: "https://www.booking.com/searchresults.html?ss={query}", Category: "travel"},
	{Shortcut: "airbnb", Name: "Airbnb", URL: "https://www.airbnb.com/s/{query}/homes", Category: "travel"},
	{Shortcut: "expedia", Name: "Expedia", URL: "https://www.expedia.com/Hotel-Search?destination={query}", Category: "travel"},
	{Shortcut: "tripadvisor", Name: "TripAdvisor", URL: "https://www.tripadvisor.com/Search?q={query}", Category: "travel", Aliases: []string{"ta"}},
	{Shortcut: "kayak", Name: "Kayak", URL: "https://www.kayak.com/explore/{query}", Category: "travel"},
	{Shortcut: "skyscanner", Name: "Skyscanner", URL: "https://www.skyscanner.com/transport/flights/search?query={query}", Category: "travel"},
	{Shortcut: "googleflights", Name: "Google Flights", URL: "https://www.google.com/travel/flights?q={query}", Category: "travel", Aliases: []string{"gflights"}},
	{Shortcut: "flightaware", Name: "FlightAware", URL: "https://flightaware.com/live/search?q={query}", Category: "travel"},
	{Shortcut: "rome2rio", Name: "Rome2rio", URL: "https://www.rome2rio.com/s/{query}", Category: "travel"},
	{Shortcut: "seat61", Name: "Seat61", URL: "https://www.seat61.com/search.htm?q={query}", Category: "travel"},
	{Shortcut: "hostelworld", Name: "Hostelworld", URL: "https://www.hostelworld.com/search?search_keywords={query}", Category: "travel"},
	{Shortcut: "vrbo", Name: "VRBO", URL: "https://www.vrbo.com/search?destination={query}", Category: "travel"},
	{Shortcut: "hotels", Name: "Hotels.com", URL: "https://www.hotels.com/Hotel-Search?destination={query}", Category: "travel"},
	{Shortcut: "agoda", Name: "Agoda", URL: "https://www.agoda.com/search?city={query}", Category: "travel"},
	{Shortcut: "lonelyplanet", Name: "Lonely Planet", URL: "https://www.lonelyplanet.com/search?q={query}", Category: "travel"},

	// ============================================================================
	// FINANCE & CRYPTO
	// ============================================================================
	{Shortcut: "yahoo", Name: "Yahoo Finance", URL: "https://finance.yahoo.com/quote/{query}", Category: "finance", Aliases: []string{"yf"}},
	{Shortcut: "gfinance", Name: "Google Finance", URL: "https://www.google.com/finance/quote/{query}", Category: "finance", Aliases: []string{"gf", "googlefinance"}},
	{Shortcut: "tradingview", Name: "TradingView", URL: "https://www.tradingview.com/symbols/{query}/", Category: "finance", Aliases: []string{"tv"}},
	{Shortcut: "marketwatch", Name: "MarketWatch", URL: "https://www.marketwatch.com/search?q={query}", Category: "finance"},
	{Shortcut: "seekingalpha", Name: "Seeking Alpha", URL: "https://seekingalpha.com/search?q={query}", Category: "finance"},
	{Shortcut: "investopedia", Name: "Investopedia", URL: "https://www.investopedia.com/search?q={query}", Category: "finance"},
	{Shortcut: "coinmarketcap", Name: "CoinMarketCap", URL: "https://coinmarketcap.com/currencies/{query}/", Category: "finance", Aliases: []string{"cmc"}},
	{Shortcut: "coingecko", Name: "CoinGecko", URL: "https://www.coingecko.com/en/search?query={query}", Category: "finance"},
	{Shortcut: "etherscan", Name: "Etherscan", URL: "https://etherscan.io/search?q={query}", Category: "finance"},
	{Shortcut: "bscscan", Name: "BscScan", URL: "https://bscscan.com/search?q={query}", Category: "finance"},
	{Shortcut: "blockchain", Name: "Blockchain.com", URL: "https://www.blockchain.com/search?search={query}", Category: "finance"},
	{Shortcut: "defi", Name: "DeFi Llama", URL: "https://defillama.com/protocol/{query}", Category: "finance", Aliases: []string{"defillama"}},
	{Shortcut: "finviz", Name: "Finviz", URL: "https://finviz.com/search.ashx?t={query}", Category: "finance"},
	{Shortcut: "stocktwits", Name: "Stocktwits", URL: "https://stocktwits.com/symbol/{query}", Category: "finance"},

	// ============================================================================
	// HEALTH & MEDICINE
	// ============================================================================
	{Shortcut: "webmd", Name: "WebMD", URL: "https://www.webmd.com/search/search_results/default.aspx?query={query}", Category: "health"},
	{Shortcut: "mayoclinic", Name: "Mayo Clinic", URL: "https://www.mayoclinic.org/search/search-results?q={query}", Category: "health"},
	{Shortcut: "healthline", Name: "Healthline", URL: "https://www.healthline.com/search?q1={query}", Category: "health"},
	{Shortcut: "medlineplus", Name: "MedlinePlus", URL: "https://medlineplus.gov/search/?query={query}", Category: "health"},
	{Shortcut: "drugs", Name: "Drugs.com", URL: "https://www.drugs.com/search.php?searchterm={query}", Category: "health"},
	{Shortcut: "rxlist", Name: "RxList", URL: "https://www.rxlist.com/search/rxlist/{query}", Category: "health"},
	{Shortcut: "nih", Name: "NIH", URL: "https://search.nih.gov/search?query={query}", Category: "health"},
	{Shortcut: "cdc", Name: "CDC", URL: "https://search.cdc.gov/search/?query={query}", Category: "health"},
	{Shortcut: "who", Name: "WHO", URL: "https://www.who.int/home/search-results?indexCatalogue=genericsearchindex1&searchQuery={query}", Category: "health"},

	// ============================================================================
	// LEGAL
	// ============================================================================
	{Shortcut: "findlaw", Name: "FindLaw", URL: "https://www.findlaw.com/search/?query={query}", Category: "legal"},
	{Shortcut: "justia", Name: "Justia", URL: "https://www.justia.com/search?q={query}", Category: "legal"},
	{Shortcut: "law", Name: "Law.com", URL: "https://www.law.com/search/?q={query}", Category: "legal"},
	{Shortcut: "courtlistener", Name: "CourtListener", URL: "https://www.courtlistener.com/?q={query}", Category: "legal"},
	{Shortcut: "caselaw", Name: "Caselaw Access", URL: "https://case.law/search/?q={query}", Category: "legal"},
	{Shortcut: "oyez", Name: "Oyez", URL: "https://www.oyez.org/search/{query}", Category: "legal"},
	{Shortcut: "cornell", Name: "Cornell Law", URL: "https://www.law.cornell.edu/search/site/{query}", Category: "legal"},
	{Shortcut: "patents", Name: "Google Patents", URL: "https://patents.google.com/?q={query}", Category: "legal"},
	{Shortcut: "uspto", Name: "USPTO", URL: "https://ppubs.uspto.gov/pubwebapp/static/pages/searchable/published-application/search.html?q={query}", Category: "legal"},
	{Shortcut: "trademark", Name: "USPTO Trademark", URL: "https://tmsearch.uspto.gov/bin/showfield?f=toc&state=4810%3Ah6l8dq.1.1&p_search=searchss&p_L=50&BackReference=&p_plural=yes&p_s_PARA1=&p_taession=&p_op_ALL=AND&a_default=search&a_search=Submit+Query&a_search=Submit+Query&p_s_PARA2={query}", Category: "legal"},

	// ============================================================================
	// EDUCATION
	// ============================================================================
	{Shortcut: "coursera", Name: "Coursera", URL: "https://www.coursera.org/search?query={query}", Category: "education"},
	{Shortcut: "udemy", Name: "Udemy", URL: "https://www.udemy.com/courses/search/?q={query}", Category: "education"},
	{Shortcut: "edx", Name: "edX", URL: "https://www.edx.org/search?q={query}", Category: "education"},
	{Shortcut: "khanacademy", Name: "Khan Academy", URL: "https://www.khanacademy.org/search?page_search_query={query}", Category: "education", Aliases: []string{"khan"}},
	{Shortcut: "udacity", Name: "Udacity", URL: "https://www.udacity.com/courses?search={query}", Category: "education"},
	{Shortcut: "skillshare", Name: "Skillshare", URL: "https://www.skillshare.com/search?query={query}", Category: "education"},
	{Shortcut: "linkedin", Name: "LinkedIn Learning", URL: "https://www.linkedin.com/learning/search?keywords={query}", Category: "education", Aliases: []string{"lil"}},
	{Shortcut: "pluralsight", Name: "Pluralsight", URL: "https://www.pluralsight.com/search?q={query}", Category: "education"},
	{Shortcut: "freecodecamp", Name: "freeCodeCamp", URL: "https://www.freecodecamp.org/news/search?query={query}", Category: "education", Aliases: []string{"fcc"}},
	{Shortcut: "codecademy", Name: "Codecademy", URL: "https://www.codecademy.com/search?query={query}", Category: "education"},
	{Shortcut: "brilliant", Name: "Brilliant", URL: "https://brilliant.org/search/?q={query}", Category: "education"},
	{Shortcut: "mit", Name: "MIT OpenCourseWare", URL: "https://ocw.mit.edu/search/?q={query}", Category: "education", Aliases: []string{"ocw"}},
	{Shortcut: "ted", Name: "TED", URL: "https://www.ted.com/search?q={query}", Category: "education"},
	{Shortcut: "masterclass", Name: "MasterClass", URL: "https://www.masterclass.com/search?q={query}", Category: "education"},

	// ============================================================================
	// GOVERNMENT & PUBLIC DATA
	// ============================================================================
	{Shortcut: "usagov", Name: "USA.gov", URL: "https://www.usa.gov/search?query={query}", Category: "government"},
	{Shortcut: "govuk", Name: "GOV.UK", URL: "https://www.gov.uk/search/all?keywords={query}", Category: "government"},
	{Shortcut: "data", Name: "Data.gov", URL: "https://catalog.data.gov/dataset?q={query}", Category: "government", Aliases: []string{"datagov"}},
	{Shortcut: "europeana", Name: "Europeana", URL: "https://www.europeana.eu/en/search?query={query}", Category: "government"},
	{Shortcut: "dpla", Name: "Digital Public Library", URL: "https://dp.la/search?q={query}", Category: "government"},
	{Shortcut: "loc", Name: "Library of Congress", URL: "https://www.loc.gov/search/?q={query}", Category: "government"},
	{Shortcut: "smithsonian", Name: "Smithsonian", URL: "https://www.si.edu/search?edan_q={query}", Category: "government"},
	{Shortcut: "worldbank", Name: "World Bank", URL: "https://www.worldbank.org/en/search?q={query}", Category: "government"},
	{Shortcut: "un", Name: "United Nations", URL: "https://www.un.org/en/search?query={query}", Category: "government"},
	{Shortcut: "census", Name: "US Census", URL: "https://www.census.gov/search-results.html?q={query}", Category: "government"},

	// ============================================================================
	// ANIME & MANGA
	// ============================================================================
	{Shortcut: "mal", Name: "MyAnimeList", URL: "https://myanimelist.net/search/all?q={query}", Category: "anime", Aliases: []string{"myanimelist"}},
	{Shortcut: "anilist", Name: "AniList", URL: "https://anilist.co/search/anime?search={query}", Category: "anime"},
	{Shortcut: "anidb", Name: "AniDB", URL: "https://anidb.net/search/anime/?adb.search={query}", Category: "anime"},
	{Shortcut: "kitsu", Name: "Kitsu", URL: "https://kitsu.io/anime?text={query}", Category: "anime"},
	{Shortcut: "crunchyroll", Name: "Crunchyroll", URL: "https://www.crunchyroll.com/search?q={query}", Category: "anime", Aliases: []string{"cr"}},
	{Shortcut: "funimation", Name: "Funimation", URL: "https://www.funimation.com/search/?q={query}", Category: "anime"},
	{Shortcut: "mangadex", Name: "MangaDex", URL: "https://mangadex.org/search?q={query}", Category: "anime"},
	{Shortcut: "mangaupdates", Name: "Manga Updates", URL: "https://www.mangaupdates.com/search.html?search={query}", Category: "anime", Aliases: []string{"mu"}},

	// ============================================================================
	// MISC / OTHER
	// ============================================================================
	{Shortcut: "reddit", Name: "Reddit Search", URL: "https://www.reddit.com/search/?q={query}", Category: "misc"},
	{Shortcut: "producthunt", Name: "Product Hunt", URL: "https://www.producthunt.com/search?q={query}", Category: "misc", Aliases: []string{"ph"}},
	{Shortcut: "alternativeto", Name: "AlternativeTo", URL: "https://alternativeto.net/browse/search/?q={query}", Category: "misc"},
	{Shortcut: "similarweb", Name: "SimilarWeb", URL: "https://www.similarweb.com/website/{query}", Category: "misc"},
	{Shortcut: "archive", Name: "Internet Archive", URL: "https://archive.org/search.php?query={query}", Category: "misc", Aliases: []string{"ia"}},
	{Shortcut: "pastebin", Name: "Pastebin", URL: "https://pastebin.com/search?q={query}", Category: "misc"},
	{Shortcut: "wolfram", Name: "Wolfram", URL: "https://www.wolfram.com/search/?query={query}", Category: "misc"},
	{Shortcut: "symbolab", Name: "Symbolab", URL: "https://www.symbolab.com/solver?or={query}", Category: "misc"},
	{Shortcut: "desmos", Name: "Desmos", URL: "https://www.desmos.com/calculator?lang=en", Category: "misc"},
	{Shortcut: "geogebra", Name: "GeoGebra", URL: "https://www.geogebra.org/search/{query}", Category: "misc"},
	{Shortcut: "timeanddate", Name: "Time and Date", URL: "https://www.timeanddate.com/worldclock/results.html?query={query}", Category: "misc"},
	{Shortcut: "xe", Name: "XE Currency", URL: "https://www.xe.com/currencyconverter/convert/?Amount=1&From={query}&To=USD", Category: "misc"},
	{Shortcut: "oeis", Name: "OEIS", URL: "https://oeis.org/search?q={query}", Category: "misc"},
}
